export const environment = {
	production: true,
	apiAxiomUrl: 'https://apiaxiom.invictusdigisoft.com',
	apiSisUrl: 'https://apisis.invictusdigisoft.com',
	apiFeeUrl: 'https://apifee.invictusdigisoft.com',
	apiSmartUrl: 'https://apismart.invictusdigisoft.com',
	apiExamUrl: 'https://apiexam.invictusdigisoft.com',
	apiReservUrl: 'https://apireservoir.invictusdigisoft.com',
	apiHRUrl: 'https://apihr.invictusdigisoft.com',
	apiInvUrl: 'http://apiinventory.invictusdigisoft.com',
	logoutUrl: 'https://login.invictusdigisoft.com',
	socketUrl: 'https://sockets.invictusdigisoft.com',
	testInitiateCode : 'T100',
	testStartCode : 'T101',
	testOngoingCode : 'T102',
	testSubmitCode : 'T103',
	testInternetErrorCode : 'T104',
	testSuspiciousErrorCode : 'T105',
	testExtendCode: 'T106',
	testEndCode: 'T107'
};
