export const environment = {
	production: true,
	apiAxiomUrl: 'http://dev-api-axiom.invictusprojects.in',
	apiSisUrl: 'http://dev-api-sis.invictusprojects.in',
	apiFeeUrl: 'http://dev-api-fee.invictusprojects.in',
	apiSmartUrl: 'http://dev-api-smart.invictusprojects.in',
	apiExamUrl: 'http://dev-api-exam.invictusprojects.in',
	apiReservUrl: 'http://dev-api-reservoir.invictusprojects.in',
	apiHRUrl: 'http://dev-api-hrms.invictusprojects.in',
	apiInvUrl: 'http://dev-api-inventory.invictusprojects.in',
	logoutUrl: 'http://devlogin.invictusprojects.in',
	socketUrl: 'http://13.234.2.36:8081',
	testInitiateCode : 'T100',
	testStartCode : 'T101',
	testOngoingCode : 'T102',
	testSubmitCode : 'T103',
	testInternetErrorCode : 'T104',
	testSuspiciousErrorCode : 'T105',
	testExtendCode: 'T106',
	testEndCode: 'T107',
	firebase: {
		apiKey: 'AIzaSyAg88lKw0PB73i3wI_fnyNbk_sdWU2VTQU',
		authDomain: 'test-notification-17c3a.firebaseapp.com',
		databaseURL: 'https://test-notification-17c3a.firebaseio.com',
		projectId: 'test-notification-17c3a',
		storageBucket: 'test-notification-17c3a.appspot.com',
		messagingSenderId: '7217963122',
		appId: '1:7217963122:web:a8b0e7b9743e355a92e2eb',
		measurementId: 'G-6DBS3LE9LF'
	}
};