export const environment = {
	production: true,
	apiAxiomUrl: 'https://apiaxiom.invictusdigisoft.com',
	apiSisUrl: 'https://apisis.invictusdigisoft.com',
	apiFeeUrl: 'https://apifee.invictusdigisoft.com',
	apiSmartUrl: 'https://apismart.invictusdigisoft.com',
	apiExamUrl: 'https://apiexam.invictusdigisoft.com',
	apiReservUrl: 'https://apireservoir.invictusdigisoft.com',
	apiHRUrl: 'https://apihr.invictusdigisoft.com',
	apiInvUrl: 'https://apiinventory.invictusdigisoft.com',
	apiFaUrl: 'https://apifa.invictusdigisoft.com',
	logoutUrl: 'https://login.invictusdigisoft.com',
	socketUrl: 'https://sockets.invictusdigisoft.com',
	helpDeskUrl: "https://support.invictusdigisoft.com/autologin.php",
	testInitiateCode : 'T100',
	testStartCode : 'T101',
	testOngoingCode : 'T102',
	testSubmitCode : 'T103',
	testInternetErrorCode : 'T104',
	testSuspiciousErrorCode : 'T105',
	testExtendCode: 'T106',
	testEndCode: 'T107',
	firebase: {
		apiKey: "AIzaSyAD31jc55BGw7Iiic79wFLUsrBEqQTkGTM",
		authDomain: "invictus-erp.firebaseapp.com",
		databaseURL: "https://invictus-erp.firebaseio.com",
		projectId: "invictus-erp",
		storageBucket: "invictus-erp.appspot.com",
		messagingSenderId: "103028680703",
		appId: "1:103028680703:web:318e4f721b2c4fdbcb29ca",
		measurementId: "G-4KS52C6DVQ"
	}
};
