export const environment = {
	production: true,
	apiAxiomUrl: 'http://uat-api-axiom.invictusprojects.in',
	apiSisUrl: 'http://uat-api-sis.invictusprojects.in',
	apiFeeUrl: 'http://uat-api-fee.invictusprojects.in',
	apiSmartUrl: 'http://uat-api-smart.invictusprojects.in',
	apiExamUrl: 'http://uat-api-exam.invictusprojects.in',
	apiReservUrl: 'http://uat-api-reservoir.invictusprojects.in',
	apiHRUrl: 'http://uat-api-hrms.invictusprojects.in',
	apiInvUrl: 'http://uat-api-inventory.invictusprojects.in',
	logoutUrl: 'http://uatlogin.invictusprojects.in',
	socketUrl: 'http://13.127.2.18:8081',
	testInitiateCode : 'T100',
	testStartCode : 'T101',
	testOngoingCode : 'T102',
	testSubmitCode : 'T103',
	testInternetErrorCode : 'T104',
	testSuspiciousErrorCode : 'T105',
	testExtendCode: 'T106',
	testEndCode: 'T107'
};
