export const environment = {
	production: false,
	apiAxiomUrl: 'http://localhost/invictus/axiom-backend/index.php',
	apiSisUrl: 'http://localhost/invictus/sis-backend/index.php',
	apiFeeUrl: 'http://localhost/invictus/feesmanagementbackend/index.php',
	apiSmartUrl: 'http://localhost/invictus/smartbackend/index.php',
	apiExamUrl: 'http://localhost/invictus/examination-backend/index.php',
	apiReservUrl: 'http://localhost/invictus/reservoir-backend/index.php',
	apiHRUrl: 'http://localhost:3000',
	apiInvUrl: 'http://localhost:3010',
	logoutUrl: 'http://devlogin.invictusprojects.in',
	socketUrl: 'http://13.234.2.36:8081',
	testInitiateCode: 'T100',
	testStartCode: 'T101',
	testOngoingCode: 'T102',
	testSubmitCode: 'T103',
	testInternetErrorCode: 'T104',
	testSuspiciousErrorCode: 'T105',
	testExtendCode: 'T106',
	testEndCode: 'T107',
	firebase: {
		apiKey: 'AIzaSyAg88lKw0PB73i3wI_fnyNbk_sdWU2VTQU',
		authDomain: 'test-notification-17c3a.firebaseapp.com',
		databaseURL: 'https://test-notification-17c3a.firebaseio.com',
		projectId: 'test-notification-17c3a',
		storageBucket: 'test-notification-17c3a.appspot.com',
		messagingSenderId: '7217963122',
		appId: '1:7217963122:web:a8b0e7b9743e355a92e2eb',
		measurementId: 'G-6DBS3LE9LF'
	}
};