export const environment = {
	production: false,
	apiAxiomUrl: 'http://localhost:83/axiom-backend/index.php',
	apiSisUrl: 'http://localhost:83/sis-backend/index.php',
	apiFeeUrl: 'http://13.234.2.36/feesmanagementbackend/index.php',
	apiSmartUrl: 'http://13.234.2.36/smartbackend/index.php',
	apiExamUrl: 'http://13.234.2.36/examination-backend/index.php',
	apiReservUrl: 'http://localhost:83/reservoir-backend/index.php',
	apiHRUrl: 'http://localhost:3000',
	logoutUrl: 'http://devlogin.invictusprojects.in',
	socketUrl: 'http://13.234.2.36:8081',
	testInitiateCode: 'T100',
	testStartCode: 'T101',
	testOngoingCode: 'T102',
	testSubmitCode: 'T103',
	testInternetErrorCode: 'T104',
	testSuspiciousErrorCode: 'T105',
	testExtendCode: 'T106',
	testEndCode: 'T107'
};