export const environment = {
	production: false,
	apiAxiomUrl: 'http://dev-api-axiom.invictusprojects.in',
	apiSisUrl: 'http://localhost/fresh/sis-backend/index.php',
	apiFeeUrl: 'http://localhost:80/feesmanagementbackend/index.php',
	apiSmartUrl: 'http://dev-api-smart.invictusprojects.in',
	apiExamUrl: 'http://localhost:80/examination-backend/index.php',
	apiReservUrl: 'http://localhost:80/reservoir-backend/index.php',
	apiHRUrl: 'http://localhost:8087',
	apiInvUrl: 'http://localhost:8086',
	apiFaUrl: 'http://localhost:8088',
	apiTransportUrl: 'http://localhost:8085',
	logoutUrl: 'http://devlogin.invictusprojects.in',
	socketUrl: 'http://socket.invictusprojects.in',
	helpDeskUrl: "http://support.invictusprojects.in/autologin.php",
	helpDeskAgentUrl: "http://support.invictusprojects.in/scp/login.php",
	payuApi : 'https://test.payu.in/_payment',
	googleMapsKey: 'AIzaSyBzZKGGAmLHnrhPdQviisk0QtSWBe-HFpI',
	testInitiateCode : 'T100',
	testStartCode : 'T101',
	testOngoingCode : 'T102',
	testSubmitCode : 'T103',
	testInternetErrorCode : 'T104',
	testSuspiciousErrorCode : 'T105',
	testExtendCode: 'T106',
	testEndCode: 'T107',
	firebase: {
		apiKey: 'AIzaSyAg88lKw0PB73i3wI_fnyNbk_sdWU2VTQU',
		authDomain: 'test-notification-17c3a.firebaseapp.com',
		databaseURL: 'https://test-notification-17c3a.firebaseio.com',
		projectId: 'test-notification-17c3a',
		storageBucket: 'test-notification-17c3a.appspot.com',
		messagingSenderId: '7217963122',
		appId: '1:7217963122:web:a8b0e7b9743e355a92e2eb',
		measurementId: 'G-6DBS3LE9LF'
	}
};
