export interface Element {
  tv_id: any,
  bus_number: any,
  bus_details: any,
  registration_no: any,
  registration_valid_upto: any,
  permit_valid_upto: any,
  insurance_valid_upto: any,
  puc_valid_upto: any,
  insurance_provider: any,
  bus_image: any,
  insurance_no: any,
  chasis_no: any,
  engine_no: any,
  device_no: any,
  driver_id: any,
  conductor_id: any,
  supervisor_id: any,
  documents: any,
  status: any,
  action:any
  }